x-airflow-common:
  &airflow-common
  build:
    context: .
    dockerfile: Dockerfile
  image: spotify_etl_airflow
  environment:
    &airflow-common-env
    AIRFLOW__CORE__SQL_ALCHEMY_CONN: sqlite:////usr/local/airflow/db/airflow.db
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
  volumes:
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
    - ./db:/usr/local/airflow/db
    - ./raw_data:/opt/airflow/raw_data
    - ./processed_data:/opt/airflow/processed_data
  user: "${AIRFLOW_UID:-50000}:${AIRFLOW_GID:-50000}"

services:
  airflow-init:
    <<: *airflow-common
    entrypoint: ["/bin/bash", "-c"]
    command: |
      airflow db init && \
      airflow db upgrade && \
      airflow users create -r Admin -u admin -e airflow@airflow.com -f admin -l user -p airflow
    environment:
      <<: *airflow-common-env

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    environment:
      <<: *airflow-common-env
    restart: always

  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - 8083:8080
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always
    environment:
      <<: *airflow-common-env
